const API="https://script.google.com/macros/s/AKfycbwOMEKjkIRnLWI2IDoHzhPEeoRb_PLZ7yvZZAzEvhBR00BoX2ASG99rQ5BPHacN9m29YQ/exec";
let products=[],level="brand",sel={brand:"",model:"",generation:"",category:""};const grid=document.getElementById("grid"),crumb=document.getElementById("crumb"),back=document.getElementById("back"),title=document.getElementById("title");
function uniq(key,arr=products){return [...new Set(arr.map(x=>String(x[key]||"").trim()).filter(Boolean))]}
function makeCard(name,sub,fn,img){let d=document.createElement("div");d.className="card";d.innerHTML=`<div class="thumb">${img?`<img src="${esc(img)}" loading="lazy">`:`${esc(name)}`}</div><div class="body"><small>SELECT</small><h3>${esc(name)}</h3><p>${esc(sub||"")}</p></div>`;d.onclick=fn;return d}
function productCard(p){let img=(p.images||[])[0];let d=makeCard(p.productName,p.category,p&&(()=>showProduct(p)),img);d.querySelector(".body").insertAdjacentHTML("beforeend",`<p class="price">${esc(p.price)}</p>`);return d}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function render(){grid.className="card-grid";grid.innerHTML="";back.disabled=level==="brand";if(level==="brand"){title.textContent="SELECT CAR BRAND";crumb.textContent="1 / BRAND";uniq("brand").forEach(x=>grid.appendChild(makeCard(x,"",()=>{sel.brand=x;level="model";render()})))}else if(level==="model"){title.textContent=sel.brand;crumb.textContent=`2 / ${sel.brand} / MODEL`;uniq("model",products.filter(p=>p.brand===sel.brand)).forEach(x=>grid.appendChild(makeCard(x,"",()=>{sel.model=x;level="generation";render()})))}else if(level==="generation"){title.textContent=sel.model;crumb.textContent=`3 / ${sel.brand} / ${sel.model} / GENERATION`;uniq("generation",products.filter(p=>p.brand===sel.brand&&p.model===sel.model)).forEach(x=>grid.appendChild(makeCard(x,"",()=>{sel.generation=x;level="category";render()})))}else if(level==="category"){title.textContent=sel.generation;crumb.textContent=`4 / ${sel.model} / ${sel.generation} / CATEGORY`;["ALL PRODUCTS",...uniq("category",products.filter(p=>p.brand===sel.brand&&p.model===sel.model&&p.generation===sel.generation))].filter((v,i,a)=>a.indexOf(v)===i).forEach(x=>grid.appendChild(makeCard(x==="ALL PRODUCTS"?x:x,"Browse products",()=>{sel.category=x;level="products";render()})))}else{title.textContent=sel.category;crumb.textContent=`5 / ${sel.model} / ${sel.generation} / ${sel.category}`;let list=products.filter(p=>p.brand===sel.brand&&p.model===sel.model&&p.generation===sel.generation);if(sel.category!=="ALL PRODUCTS")list=list.filter(p=>p.category===sel.category);list.forEach(p=>grid.appendChild(productCard(p)));}}
function showProduct(p){grid.className="";grid.innerHTML=`<div class="detail"><div class="gallery">${(p.images||[]).length?(p.images||[]).map(u=>`<img src="${esc(u)}" loading="lazy">`).join(""):`<div class="empty-img">PRODUCT PHOTO</div>`}</div><div class="copy"><small>${esc(p.brand)} · ${esc(p.model)} · ${esc(p.generation)}</small><h3>${esc(p.productName)}</h3><div class="bigprice">${esc(p.price)}</div><p>${esc(p.description)}</p><div class="spec"><div><b>MATERIAL</b><br>${esc(p.material)}</div><div><b>FINISH</b><br>${esc(p.finish)}</div><div><b>CATEGORY</b><br>${esc(p.category)}</div><div><b>INSTALLATION</b><br>Available</div></div><br><a class="btn" href="https://wa.me/" target="_blank">WHATSAPP TO ORDER →</a></div></div>`}
back.onclick=()=>{if(level==="model")level="brand";else if(level==="generation")level="model";else if(level==="category")level="generation";else if(level==="products")level="category";render()};
fetch(API).then(r=>r.json()).then(d=>{products=d.map(p=>({...p,images:p.images||[]}));render()}).catch(e=>{grid.className="";grid.innerHTML='<p style="color:#e62b2b">Unable to load Google Sheet. Check that the Apps Script deployment is set to Anyone.</p>';});
